spring:
    profiles:
      active: dev
    mail:
      host: smtp.mxhichina.com
      port: 25
      username: stock@just-love.cn
      password: Taobao1234
    thymeleaf:
      suffix: .html
      content-type: text/html
      mode: HTML5
      prefix: classpath:/statics/
      encoding: UTF-8
    velocity:
      check-template-location: false
mybatis:
  mapper-locations: classpath*:org/eddy/dao/mapper/*/*.xml
