spring:
  datasource:
    name: stock
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'T' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false