spring:
  datasource:
    name: stock
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.99.100:3306/stock?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 3
    maxActive: 10
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'T' FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
  thymeleaf:
    cache: false
stock:
  url: https://oapi.dingtalk.com/robot/send
  arg: access_token
